# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.14.5/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.14.5/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/platypus/uib/ODDs

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/platypus/uib/ODDs

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.14.5/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.14.5/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.14.5/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.14.5/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.14.5/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.14.5/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.14.5/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.14.5/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.14.5/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/platypus/uib/ODDs/CMakeFiles /Users/platypus/uib/ODDs/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/platypus/uib/ODDs/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ODDsTest

# Build rule for target.
ODDsTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ODDsTest
.PHONY : ODDsTest

# fast build rule for target.
ODDsTest/fast:
	$(MAKE) -f CMakeFiles/ODDsTest.dir/build.make CMakeFiles/ODDsTest.dir/build
.PHONY : ODDsTest/fast

#=============================================================================
# Target rules for targets named ODDs

# Build rule for target.
ODDs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ODDs
.PHONY : ODDs

# fast build rule for target.
ODDs/fast:
	$(MAKE) -f CMakeFiles/ODDs.dir/build.make CMakeFiles/ODDs.dir/build
.PHONY : ODDs/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f ext/googletest/googlemock/CMakeFiles/gmock.dir/build.make ext/googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f ext/googletest/googlemock/CMakeFiles/gmock_main.dir/build.make ext/googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f ext/googletest/googletest/CMakeFiles/gtest_main.dir/build.make ext/googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f ext/googletest/googletest/CMakeFiles/gtest.dir/build.make ext/googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

lib/ODDs.o: lib/ODDs.cpp.o

.PHONY : lib/ODDs.o

# target to build an object file
lib/ODDs.cpp.o:
	$(MAKE) -f CMakeFiles/ODDs.dir/build.make CMakeFiles/ODDs.dir/lib/ODDs.cpp.o
.PHONY : lib/ODDs.cpp.o

lib/ODDs.i: lib/ODDs.cpp.i

.PHONY : lib/ODDs.i

# target to preprocess a source file
lib/ODDs.cpp.i:
	$(MAKE) -f CMakeFiles/ODDs.dir/build.make CMakeFiles/ODDs.dir/lib/ODDs.cpp.i
.PHONY : lib/ODDs.cpp.i

lib/ODDs.s: lib/ODDs.cpp.s

.PHONY : lib/ODDs.s

# target to generate assembly for a file
lib/ODDs.cpp.s:
	$(MAKE) -f CMakeFiles/ODDs.dir/build.make CMakeFiles/ODDs.dir/lib/ODDs.cpp.s
.PHONY : lib/ODDs.cpp.s

test/Sample.o: test/Sample.cpp.o

.PHONY : test/Sample.o

# target to build an object file
test/Sample.cpp.o:
	$(MAKE) -f CMakeFiles/ODDsTest.dir/build.make CMakeFiles/ODDsTest.dir/test/Sample.cpp.o
.PHONY : test/Sample.cpp.o

test/Sample.i: test/Sample.cpp.i

.PHONY : test/Sample.i

# target to preprocess a source file
test/Sample.cpp.i:
	$(MAKE) -f CMakeFiles/ODDsTest.dir/build.make CMakeFiles/ODDsTest.dir/test/Sample.cpp.i
.PHONY : test/Sample.cpp.i

test/Sample.s: test/Sample.cpp.s

.PHONY : test/Sample.s

# target to generate assembly for a file
test/Sample.cpp.s:
	$(MAKE) -f CMakeFiles/ODDsTest.dir/build.make CMakeFiles/ODDsTest.dir/test/Sample.cpp.s
.PHONY : test/Sample.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... install/local"
	@echo "... test"
	@echo "... ODDsTest"
	@echo "... list_install_components"
	@echo "... ODDs"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... lib/ODDs.o"
	@echo "... lib/ODDs.i"
	@echo "... lib/ODDs.s"
	@echo "... test/Sample.o"
	@echo "... test/Sample.i"
	@echo "... test/Sample.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

